apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift
spec:
  containers:
  - name: hello-openshift
    image: image-registry.openshift-image-registry.svc:5000/<your_namespace>/hello-openshift
    env:
      # learn about the downward api https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api
    - name: HELLO
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    ports:
    - name: web
      containerPort:
      protocol: TCP
